name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.0.0', '2.2.7', '2.3.4', '2.4.1', '2.5.5', '3.0.0', '3.3.6']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          cache: bundler

      - name: Install Bundler
        run: gem install bundler -v 2.5.23

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake test